name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
  branches: [master]
pull_request:
  branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
       node-version: [17.1]
    steps:
        -uses: actions/checkout@v4 
        -name: Starting Node.js ${{matrix.node-version}}   
          uses: actions/setuo-node@v4 
          with: 
            node-version: ${{matrix.node-version}}
        -name: install modules
        run: npm install
        -name: build project
        run: npm run build
        -name: unit test
        run: npm run test:unit
        -name: e2e test
        run: npm run test:e2e
